{{- if .Values.secret }}
{{- range .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .metadata.name }}
  namespace: {{ $.Release.Namespace }}
type: {{ .type | default "Opaque" }}
stringData:
  {{- toYaml .stringData | nindent 2 }}
{{- end }}
{{- end }}
